name: Spring Boot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/api/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven (Skip Tests)
      run: mvn clean install -DskipTests --no-transfer-progress
      working-directory: ./api

    - name: Run tests
      run: mvn test --no-transfer-progress
      working-directory: ./api
      continue-on-error: true

    - name: Post-build steps
      if: success() || failure()
      run: echo "Build and test completed"
